{"componentChunkName":"component---src-templates-blog-post-js","path":"/2007/01/duplicity-error/","result":{"data":{"site":{"siteMetadata":{"domain":"https://www.docunext.com"}},"markdownRemark":{"html":"<pre>\nTraceback (most recent call last):  File \"/usr/src/duplicity/duplicity-bin\", line 373, in ?    if __name__ == \"__main__\": main()  File \"/usr/src/duplicity/duplicity-bin\", line 366, in main    if not sig_chain: full_backup(col_stats)  File \"/usr/src/duplicity/duplicity-bin\", line 142, in full_backup    bytes_written = write_multivol(\"full\", tarblock_iter, globals.backend)  File \"/usr/src/duplicity/duplicity-bin\", line 91, in write_multivol    tdp.delete()  File \"/usr/src/duplicity/duplicity/dup_temp.py\", line 92, in delete    path.DupPath.delete(self)  File \"/usr/src/duplicity/duplicity/path.py\", line 468, in delete    else: os.unlink(self.name)\n\nOSError: [Errno 2] No such file or directory: '/tmp/tmpUzWvD3'</pre>\n<p>This results in:</p>\n<pre>Warning, found incomplete backup sets, probably left from aborted session</pre>\n<p>which isn't cool.</p>","fields":{"slug":"/2007/01/duplicity-error/"},"frontmatter":{"title":"Duplicity Error","date":"January 31st, 2007","tags":null}}},"pageContext":{"slug":"/2007/01/duplicity-error/"}}}